name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version"
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0
          token: "${{ secrets.ACCESS_TOKEN }}"
          ref: "main"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          git_name: ${{ secrets.GIT_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          changelog_increment_filename: body.md

      - name: Print Version
        run: echo "Bumped to version ${{ env.REVISION }}"

      - name: Trim body to 125000 characters
        run: |
          if [ $(wc -c < body.md) -gt 125000 ]; then
            head -c 125000 body.md > body.md
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: "true"

  build:
    runs-on: ubuntu-latest
    needs:
      - bump_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false

      - name: Set repo name
        run: |
          repo=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO=$repo" >> $GITHUB_ENV

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REPO }}:latest --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REPO }}:${{ needs.bump_version.outputs.version }} --push .
